title: Hyde
description: Site estático no GitHub Pages usando tema remoto Hyde Primeira parte
url: "https://veronicarlima.github.io"
baseurl: "" # deixe vazio se for repositório user/organization pages

remote_theme: poole/hyde
plugins:
  - jekyll-remote-theme

# Opções extras do Hyde
theme: jekyll-theme-primer # ignora no GitHub Pages, mas evita warnings locais
paginate: 5
