# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

#Setup
title: "Veronica Lima"
description: "Meu portfólio e projetos pessoais"
theme: jekyll-theme-hyde
url: "https://veronicalima.github.io"
baseurl: "https://veronicarlima.github.io/"
author:
  name: "Veronica Lima"
  email: "veronica@email.com"

# opções do Hyde
sidebar:
  title: "About mee"
  description: "Full Stack Developer focused on building reliable, scalable, and elegant web solutions."

paginate:         5

# Custom vars
version:          2.1.0