#url: "https://veronicarlima.github.io"
#baseurl: "" # deixe vazio se for repositório user/organization pages

remote_theme: academicpages/academicpages.github.io
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
